default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: newapplication_development
test:
  <<: *default
  database: newapplication_test
production:
  <<: *default
  database: newapplication_production
  username: newapplication
  password: <%= ENV['NEWAPPLICATION_DATABASE_PASSWORD'] %>
